### ISSUE TITLE
Calendar displays wrong day numbers

### ISSUE THREAD

**Issue by demianlicht** [frappe/books#107]
On the setup screen, and on all subsequent screens, when I click on the popover calendar I get a weird issue. Basically, the calendar works correctly in the sense that the date I choose is passed along nicely. However, I am at a lost as to which date I'm picking because all dates display 18, 20, 22, 24, 26, 28 and then 30 from then on, as shown in the screenshot:
![Screen Shot 2019-12-17 at 10 17 53](https://user-images.githubusercontent.com/11319138/71013973-c89b9e80-20b6-11ea-9f39-bf50c3badb31.png)

Any clues as to why this might be happening? It seems to me that it is somehow picking up only the "even" dates and then it's not looping past 30, but I am at a loss as to how to fix it.

**Comment by demianlicht** [comment]
Forgot to add that this happens on both MacOS 10 and Win10.

**Comment by netchampfaris** [comment]
@demianlicht This is fixed in the latest version. Can you confirm?

**Comment by nestorwheelock** [comment]
I ran into this too downloading and running the app image that is released on frappebooks.com.  The error persists when returning to edit the settings after finishing the setup dialogue.  I was using xubuntu 18.04.  The dates do seem to change a little but the pattern is similar.  I also received a pop up alert notification even when I filled in the form.  If that's unrelated I can report that in a new issue.
![Date-picker-bug4](https://user-images.githubusercontent.com/33142680/72912078-b689cd00-3d00-11ea-8faf-8b086904c020.png)
![Date-picker-bug3](https://user-images.githubusercontent.com/33142680/72912079-b689cd00-3d00-11ea-879d-186ca6f1306e.png)
![Date-picker-bug2](https://user-images.githubusercontent.com/33142680/72912080-b689cd00-3d00-11ea-9185-446f16ea8b6c.png)
![Date-picker-bug](https://user-images.githubusercontent.com/33142680/72912081-b689cd00-3d00-11ea-9e06-9b23a805f359.png)

**Comment by Franklin0702** [comment]
> @demianlicht This is fixed in the latest version. Can you confirm?

Nope. Error Persist.

**Comment by jcastillopro** [comment]
Hi, the same thing happens to me. please appreciate the support!

**Comment by MaxMorais** [comment]
I'm also having that issue on Ubuntu 18.04, Brazilian Location UTF-8 (PT-BR)

**Comment by demianlicht** [comment]
Hi, still persistent.

**Comment by Franklin0702** [comment]
Hello everyone, 

To solve this (temporarily) I commented the next line in **getDate** function inside **DatePicker.vue file**:
![image](https://user-images.githubusercontent.com/19265450/78467207-31e00580-76d8-11ea-935c-2ad695fd8130.png)

the file is in the following path: src/component/DatePicker/DatePicker.vue

Hope this helps.

**Comment by gonrial** [comment]
Linux too Release 0.0.3-beta.12 
![Captura de pantalla de 2020-05-06 18-53-36](https://user-images.githubusercontent.com/475469/81232381-3182a500-8fcb-11ea-8b9b-376f4025a904.png)

**Comment by mding5692** [comment]
**MacOS v0.0.3-beta.11**

Issue still persists:

![Screen Shot 2020-05-09 at 7 05 35 PM](https://user-images.githubusercontent.com/9067177/81487104-3abc7d80-9228-11ea-9439-f9f78be8549e.png)

**Comment by mding5692** [comment]
Looks like the commit here: https://github.com/frappe/books/commit/df6ace3b8d6837be0ec82b2ff6c5fa57e1fed5ba
introduced in on line 204:
`return new Date(d.getTime() - d.getTimezoneOffset() * 60000);`

Once commented it out and then replaced with:
`return d;`

it seems to not generate the same issue anymore as stated by @Fatman452 

See:
![Screen Shot 2020-05-09 at 8 31 47 PM](https://user-images.githubusercontent.com/9067177/81488228-28484100-9234-11ea-94ac-aa219eac7c56.png)

Might want to consider removing that line or reimplementing it as its breaking the DatePicker component

My current country selected is Canada and timezone is Eastern Daylight Time (EDT) and 
this code: 
`d.getTimezoneOffset()` returns 240

and printing out whole statement from:
`new Date(d.getTime() - d.getTimezoneOffset() * 60000);` 
gives: Wed Oct 16 2019 16:00:00 GMT-0400 (Eastern Daylight Time)

and printing out `new Date(...args)` gives me:
Wed Oct 16 2019 20:00:00 GMT-0400 (Eastern Daylight Time)

Whats the reason for adding this line which is breaking the calendar? @netchampfaris

**Comment by netchampfaris** [comment]
@mding5692 Hey, thanks for your analysis. I don't remember correctly but I think I did that to get UTC time. Which I guess is not needed for a local app 😅

Sent a fix: https://github.com/frappe/books/commit/d9bd73642b469482ce529f302896937048e62e87
